import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import AuthProvider from "@/context/auth-provider";
import { SessionProvider } from "next-auth/react";
import { SocketProvider } from "@/context/socket-provider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Alochona | Home",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <Suspense>
          <SessionProvider>
            <AuthProvider>
              <TRPCReactProvider>
                <SocketProvider>{children}</SocketProvider>
              </TRPCReactProvider>
            </AuthProvider>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
